---
# This playbook deploys the whole application stack in this site.

- hosts: all-servers
  connection: local
  gather_facts: no
  tasks:
    - name: Power off servers
      oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ ov_username }}"
        password: "{{ ov_password }}"
        name: "{{ inventory_hostname }}"
        state: powered_off
      ignore_errors: true

    - name: Delete server
      oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ ov_username }}"
        password: "{{ ov_password }}"
        name: "{{ inventory_hostname }}"
        state: absent
      ignore_errors: true
