###
# Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Storage Volume Attachments
      oneview_storage_volume_attachment_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=storage_volume_attachments
    
    
    - name: Gather facts about a Storage Volume Attachment by Server Profile Name and Volume Uri
      oneview_storage_volume_attachment_facts:
        config: "{{ config }}"
        serverProfileName: "sp-bdd"
        storageVolumeUri: "/rest/storage-volumes/89118052-A367-47B6-9F60-F26073D1D85E"
      delegate_to: localhost

    - debug: var=storage_volume_attachments
    
    
    - name: Gather facts about extra unmanaged storage volumes
      oneview_storage_volume_attachment_facts:
        config: "{{ config }}"
        options:
          - extraUnmanagedStorageVolumes:
                start: 0
                count: 10
      delegate_to: localhost

    - debug: var=storage_volume_attachments
    - debug: var=extra_unmanaged_storage_volumes


    - name: Gather facts about volume attachment paths
      oneview_storage_volume_attachment_facts:
        config: "{{ config }}"
        serverProfileName: "sp-bdd"
        storageVolumeName: "volume-attachment-demo"
        options:
          - paths
      delegate_to: localhost

    - debug: var=storage_volume_attachments
    - debug: var=storage_volume_attachment_paths


    - name: Gather facts about volume attachment path by id
      oneview_storage_volume_attachment_facts:
        config: "{{ config }}"
        serverProfileName: "sp-bdd"
        storageVolumeName: "volume-attachment-demo"
        options:
          - paths:
                pathId: '9DFC8953-15A4-4EA9-AB65-23AE663F48D4'
      delegate_to: localhost

    - debug: var=storage_volume_attachments
    - debug: var=storage_volume_attachment_paths
