---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Fibre Channel Networks
      oneview_fc_network_facts:
        config: "{{ config }}"
      register: result
    - debug: var=result

    - name: Gather facts about a Fibre Channel Network by name
      oneview_fc_network_facts:
        config: "{{ config }}"
        name: "Test FC Network"
      register: result
    - debug: var=result
