###
# (C) Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Create a Logical Interconnect Group
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
          type: 'logical-interconnect-groupV3'
          name: 'Test Logical Interconnect Group'
          uplinkSets: []
          enclosureType: 'C7000'
          interconnectMapTemplate:
            interconnectMapEntryTemplates: []
      delegate_to: localhost

    - name: Do nothing with the Logical Interconnect Group when no changes are provided
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test Logical Interconnect Group'
          enclosureType: 'C7000'
      delegate_to: localhost

    - name: Update the Logical Interconnect Group changing the attribute description to 'New Description'
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test Logical Interconnect Group'
          description: 'New Description'
      delegate_to: localhost

    - name: Rename the Logical Interconnect Group to 'Updated Logical Interconnect Group'
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test Logical Interconnect Group'
          newName: 'Updated Logical Interconnect Group'
      delegate_to: localhost

    - name: Delete the Logical Interconnect Group
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: absent
        data:
          name: 'Updated Logical Interconnect Group'
      delegate_to: localhost
      register: deleted

    - name: Do nothing when Logical Interconnect Group is absent
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: absent
        data:
          name: 'Updated Logical Interconnect Group'
      delegate_to: localhost
      register: deleted