###
# (C) Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Create a Fibre Channel Network
      oneview_fc_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FC Network'
      delegate_to: localhost
      register: fc_network_1

    - name: Should not create or update the Fibre Channel Network with no changes provided
      oneview_fc_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FC Network'
          fabricType: 'FabricAttach'
      delegate_to: localhost

    - name: Should update the Fibre Channel Network changing the attribute autoLoginRedistribution to True
      oneview_fc_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FC Network'
          autoLoginRedistribution: True
      delegate_to: localhost

    - name: Delete the Fibre Channel Network
      oneview_fc_network:
        config: "{{ config }}"
        state: absent
        data: "{{ fc_network_1.ansible_facts.fc_network }}"
      delegate_to: localhost
      register: deleted

    - name: Do nothing when Fibre Channel Network is absent
      oneview_fc_network:
        config: "{{ config }}"
        state: absent
        data: "{{ fc_network_1.ansible_facts.fc_network }}"
      delegate_to: localhost
      register: deleted
