###
# (C) Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Create a FCoE Network
      oneview_fcoe_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FCoE Network'
          vlanId: '201'
      delegate_to: localhost
      register: fcoe_network_1

    - name: Should not create or update the FCoE Network with no changes provided
      oneview_fcoe_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FCoE Network'
          vlanId: 201
      delegate_to: localhost
    - debug: var=result

    - name: Should update the FCoE Network changing the attribute name
      oneview_fcoe_network:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test FCoE Network - Changed'
          vlanId: 201
      delegate_to: localhost

    - name: Delete the FCoE Network
      oneview_fcoe_network:
        config: "{{ config }}"
        state: absent
        data: "{{ fcoe_network_1.ansible_facts.fcoe_network }}"
      delegate_to: localhost
      register: deleted

    - name: Do nothing when FCoE Network is absent
      oneview_fcoe_network:
        config: "{{ config }}"
        state: absent
        data: "{{ fcoe_network_1.ansible_facts.fcoe_network }}"
      delegate_to: localhost
      register: deleted
