###
# Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"

  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:

    # This play is compatible with C7000 Enclosures
    - name: Ensure the Enclosure with hostname '{{ enclosure_hostname }}' is present with name 'Test-Enclosure'
      oneview_enclosure:
        config: "{{ config }}"
        state: present
        data:
          enclosureGroupUri: '{{ enclosure_group_uri }}'
          hostname: '{{ enclosure_hostname }}'
          username: '{{ enclosure_username }}'
          password: '{{ enclosure_password }}'
          name: 'Test-Enclosure'
          licensingIntent : 'OneView'
          rackName: 'Rack-Name'
      delegate_to: localhost

    # This play is compatible with C7000 Enclosures
    - name: Do nothing with the Enclosure when no changes are provided
      oneview_enclosure:
        config: "{{ config }}"
        state: present
        data:
          enclosureGroupUri: '{{ enclosure_group_uri }}'
          hostname: '{{ enclosure_hostname }}'
          username: '{{ enclosure_username }}'
          password: '{{ enclosure_password }}'
          name: 'Test-Enclosure'
          licensingIntent : 'OneView'
          rackName: 'Rack-Name'
      delegate_to: localhost

    - name: Update the name of the enclosure to "Test-Enclosure-Renamed"
      oneview_enclosure:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test-Enclosure'
          newName: 'Test-Enclosure-Renamed'
      delegate_to: localhost

    - name: Update the name of the rack to "Rack-Renamed"
      oneview_enclosure:
        config: "{{ config }}"
        state: present
        data:
          name: 'Test-Enclosure-Renamed'
          rackName: 'Rack-Renamed'
      delegate_to: localhost

    - name: Reconfigure the enclosure "Test-Enclosure-Renamed"
      oneview_enclosure:
        config: "{{ config }}"
        state: reconfigured
        data:
          name: 'Test-Enclosure-Renamed'
      delegate_to: localhost

    - name: Refresh the enclosure along with all of its components
      oneview_enclosure:
        config: "{{ config }}"
        state: refreshed
        data:
          name: 'Test-Enclosure-Renamed'
          refreshState: 'RefreshPending'
      delegate_to: localhost

    # This state is only available for C7000 enclosures
    - name: Set the supportDataCollectionState equals to 'PendingCollection' for the enclosure
      oneview_enclosure:
        config: "{{ config }}"
        state: support_data_collection_set
        data:
          name: 'Test-Enclosure-Renamed'
          supportDataCollectionState: 'PendingCollection'
      delegate_to: localhost
      ignore_errors: yes
      register: result

    - debug: var=result.msg

    - name: Remove the Enclosure
      oneview_enclosure:
        config: "{{ config }}"
        state: absent
        data:
          name: 'Test-Enclosure-Renamed'
      delegate_to: localhost

    - name: Do nothing when Enclosure is absent
      oneview_enclosure:
        config: "{{ config }}"
        state: absent
        data:
          name: 'Test-Enclosure-Renamed'
      delegate_to: localhost

    # This state is only available on HPE Synergy.
    - name: Set the appliance bay power state on
      oneview_enclosure:
        config: "{{ config }}"
        state: appliance_bays_powered_on
        data:
          name: '0000A66101'
          bayNumber: 1
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Set the appliance UID state off
      oneview_enclosure:
        config: "{{ config }}"
        state: uid_off
        data:
          name: '0000A66101'
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Set the appliance UID state on
      oneview_enclosure:
        config: "{{ config }}"
        state: uid_on
        data:
          name: '0000A66101'
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Set the UID for the Synergy Frame Link Module state on
      oneview_enclosure:
        config: "{{ config }}"
        state: manager_bays_uid_on
        data:
          name: '0000A66101'
          bayNumber: 1
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Set the UID for the Synergy Frame Link Module state off
      oneview_enclosure:
        config: "{{ config }}"
        state: manager_bays_uid_off
        data:
          name: '0000A66101'
          bayNumber: 1
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: E-Fuse the Synergy Frame Link Module bay 1
      oneview_enclosure:
        config: "{{ config }}"
        state: manager_bays_power_state_e_fuse
        data:
          name: '0000A66101'
          bayNumber: 1
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Reset the Synergy Frame Link Module bay 2
      oneview_enclosure:
        config: "{{ config }}"
        state: manager_bays_power_state_reset
        data:
          name: '0000A66101'
          bayNumber: 2
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: E-Fuse the appliance bay 1
      oneview_enclosure:
        config: "{{ config }}"
        state: appliance_bays_power_state_e_fuse
        data:
          name: '0000A66101'
          bayNumber: 1
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: E-Fuse the device bay 10
      oneview_enclosure:
        config: "{{ config }}"
        state: device_bays_power_state_e_fuse
        data:
          name: '0000A66101'
          bayNumber: 10
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Reset the device bay 11
      oneview_enclosure:
        config: "{{ config }}"
        state: device_bays_power_state_reset
        data:
          name: '0000A66101'
          bayNumber: 11
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: E-Fuse the IC bay 3
      oneview_enclosure:
        config: "{{ config }}"
        state: interconnect_bays_power_state_e_fuse
        data:
          name: '0000A66101'
          bayNumber: 3
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Set the active Synergy Frame Link Module on bay 2
      oneview_enclosure:
        config: "{{ config }}"
        state: manager_bays_role_active
        data:
          name: '0000A66101'
          bayNumber: 2
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy.
    - name: Release IPv4 address in the device bay 3
      oneview_enclosure:
        config: "{{ config }}"
        state: device_bays_ipv4_removed
        data:
          name: '0000A66101'
          bayNumber: 3
      delegate_to: localhost
      register: result

    - debug: var=result.msg

    # This state is only available on HPE Synergy
    - name: Release IPv4 address in the interconnect bay 6
      oneview_enclosure:
        config: "{{ config }}"
        state: interconnect_bays_ipv4_removed
        data:
          name: '0000A66101'
          bayNumber: 6
      delegate_to: localhost
      register: result

    - debug: var=result.msg
