###
# (C) Copyright (2016) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- hosts: all
  vars:
    - oneview: 172.16.102.149
    - username: administrator
    - password: serveradmin
    - ov_template: 'webserver-template'
  tasks:
   - name : Create Server Profiles
     oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ username }}"
        password: "{{ password }}"
        server_template: "{{ ov_template }}"
        name: "{{ inventory_hostname }}"
     delegate_to: localhost

   - name : Power on servers
     oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: "{{ inventory_hostname }}"
        state: "powered_on"
     when: server_hardware.powerState == "Off"
     delegate_to: localhost

   - name : Power off server to fix offline remediation
     oneview_server_profile:
       oneview_host: "{{ oneview }}"
       username: "{{ username }}"
       password: "{{ password }}"
       name: "{{ inventory_hostname }}"
       state: "powered_off"
     when: server_profile.templateCompliance != "Compliant" and compliance_preview.isOnlineUpdate == False
     delegate_to: localhost

   - name : Remediate compliance issues
     oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: "{{ inventory_hostname }}"
        state: "compliant"
     when: server_profile.templateCompliance != 'Compliant'
     delegate_to: localhost

   - name : Power on server
     oneview_server_profile:
        oneview_host: "{{ oneview }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: "{{ inventory_hostname }}"
        state: "powered_on"
     when: server_hardware.powerState == "Off"
     delegate_to: localhost

   - name: Wait for server to boot
     wait_for: 'host={{ inventory_hostname }} port=22 state=started timeout=600'
     delegate_to: localhost
