 - name : Create Server Profiles
   oneview_server_profile:
      oneview_host: "{{ oneview }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      server_template: "{{ ov_template }}"
      name: "{{ inventory_hostname }}"
      #server_hardware: "{{ server_hardware }}"  Optional - if ommited, select automatically
   delegate_to: localhost

 - name : Power on servers
   oneview_server_profile:
      oneview_host: "{{ oneview }}"
      username: "{{ ov_username }}"
      password: "{{ ov_password }}"
      name: "{{ inventory_hostname }}"
      state: "powered_on"
   when: server_hardware.powerState == "Off"
   delegate_to: localhost

 - name : Deploy OS
   hp_icsp:
     icsp_host: "{{ icsp }}"
     username: "{{ icsp_username }}"
     password: "{{ icsp_password }}"
     server_id: "{{ server_profile.serialNumber }}"
     os_build_plan: "{{ os_build_plan }}"
     custom_attributes: "{{ osbp_custom_attributes }}"
     personality_data: "{{ network_config }}"
   when: created  #only if we just created the server. No re-deployment
   delegate_to: localhost
